version: "3.7"

services:
  r3-mvp-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      # reference docker target
    container_name: r3-mvp-dev
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./:/app
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:${BACKEND_PORT}/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
